# Generated by Django 5.0.6 on 2024-05-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logo',
            old_name='img',
            new_name='logo',
        ),
    ]
